### ISSUE TITLE
Detection of operating system. 

### ISSUE THREAD

**Issue by kotajacob** [kotajacob/wal_steam#24]
This would allow the program to easily work on operating system that have steam in a different location than ~/.local/share/Steam

**Comment by dylanaraps** [comment]
According to the Steam launch script, Steam is always located at `${HOME}/.steam/` which is symlinked to `${HOME}/.local/share/Steam` or wherever the steam files are located. 

Anyway, the point I'm trying to make is that `${HOME}/.steam/` should always point to the right location so you can use it in a script.

**Comment by kotajacob** [comment]
Sweet I'll test that here shortly!
