### ISSUE TITLE
More standard location for the temp downloads than resources folder.

### ISSUE THREAD

**Issue by kotajacob** [kotajacob/wal_steam#26]
Currently we're downloading the metro skin and patches to a resources folder in the repo, this should be changed to a standard that will work well with our new aur package. (and any other future packages)

**Comment by emctague** [comment]
Just a suggestion: Perhaps you could store these resources in a directory in `~/.local/share` or  `~/.cache`.

**Comment by kotajacob** [comment]
Yea, downloading to cache is a much better way of doing this. I'll be changing to that in 1.1.0 here soon.

**Comment by kotajacob** [comment]
Alright files are now stored in ~/.cache/wal_steam so that should fix this issue.
