### ISSUE TITLE
Doesn't work with wal or wpgtk

### ISSUE THREAD

**Issue by 132ikl** [kotajacob/wal_steam#31]
Version: 1.1.0. I have both wpgtk and pywal installed through pip. When I run 
wal_steam.py -w:
`Metro Wal found
Reading colors
Traceback (most recent call last):
  File "wal_steam.py", line 243, in <module>
    main(arguments)
  File "wal_steam.py", line 237, in main
    colors = parseCss(walConfig) # they picked w so parse wal
  File "wal_steam.py", line 172, in parseCss
    f_name = open(config, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/steveoy132ikl/.cache/wal/colors.css'`
wal_steam.py -g
`Metro Wal found
Reading colors
Traceback (most recent call last):
  File "wal_steam.py", line 243, in <module>
    main(arguments)
  File "wal_steam.py", line 233, in main
    colors = parseCss(wpgConfig) # they picked g so parse wpg
  File "wal_steam.py", line 172, in parseCss
    f_name = open(config, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/steveoy132ikl/.wallpapers/current.css'`

**Comment by kotajacob** [comment]
What operating system are you running and have you run wal or wpgtk alone at least once before running wal_steam?

**Comment by 132ikl** [comment]
I didn't realize you had to run wal/wpgtk alone before you ran wal_steam. You should add that to the documentation. Thanks!
