### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by AccountOneOff** [kotajacob/wal_steam#33]
Traceback (most recent call last):
      File "wal_steam.py", line 31, in <module>
        import urllib.request                     # downloading the zip files
    ImportError: No module named request

Ran `wpg` set the wallpaper `cd` into directory with wal_steam.py and ran `python wal_steam.py -g` and I received this error. I have python-urllib3 and python3-urllib3 installed.

Ubuntu 17.04 
Gnome 3.24.2

**Comment by kotajacob** [comment]
I'll try to duplicate the issue. Can you make sure python is actually referring to python 3? By running `python --version`

**Comment by AccountOneOff** [comment]
Looks like it isn't `Python 2.7.13`

**Comment by kotajacob** [comment]
Gotcha yea it looks like on ubuntu you'll need to run with python3 instead of python. I'll add it to the readme.
