### ISSUE TITLE
Script adds skin to wrong folder

### ISSUE THREAD

**Issue by AccountOneOff** [kotajacob/wal_steam#34]
Steam doesn't recognize the newly created skin when put in `~/.steam/steam/skins`. The script should be changed to `~/.steam/skins` instead. I have a skin installed in the latter folder so I don't know if that's conflicting with it.

**Comment by kotajacob** [comment]
What operating system/distro are you running? I can add some detection for that.

**Comment by AccountOneOff** [comment]
Ubuntu 17.04

**Comment by kotajacob** [comment]
Oh right yea, wow. I'll check it out quick.

**Comment by kotajacob** [comment]
I just pushed a new version that should be able to detect if your skins folder is in ~/.steam/skins or ~/.steam/steam/skins. It worked in all my testing, but I'll wait for you to confirm it's working on your end.

**Comment by AccountOneOff** [comment]
It's still putting it in ~.steam/steam/skins

**Comment by kotajacob** [comment]
Try deleting that skins folder, it should then detect the other one and place it in their. I'll be working on a more elegant fix in the future.

**Comment by AccountOneOff** [comment]
That worked. :smile:
