### ISSUE TITLE
No such file or directory: '/home/kevin/.wallpapers/current.css'

### ISSUE THREAD

**Issue by kevinsmia1939** [kotajacob/wal_steam#35]
I use Xubuntu 16.04 (xfce)
kevin@kevin-desktop:~/wal_steam$ sudo python3 wal_steam.py -g
Downloading Metro for steam
Downloading Metro patch
Installing Metro Wal
Metro Wal is now installed
Reading colors
Traceback (most recent call last):
  File "wal_steam.py", line 243, in <module>
    main(arguments)
  File "wal_steam.py", line 233, in main
    colors = parseCss(wpgConfig) # they picked g so parse wpg
  File "wal_steam.py", line 172, in parseCss
    f_name = open(config, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/kevin/.wallpapers/current.css'

**Comment by kevinsmia1939** [comment]
I install pywal not the other one, still error. 
kevin@kevin-desktop:~/wal_steam$ python3 wal_steam.py -w
Metro Wal found
Reading colors
Traceback (most recent call last):
  File "wal_steam.py", line 243, in <module>
    main(arguments)
  File "wal_steam.py", line 237, in main
    colors = parseCss(walConfig) # they picked w so parse wal
  File "wal_steam.py", line 172, in parseCss
    f_name = open(config, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/kevin/.cache/wal/colors.css'

**Comment by kotajacob** [comment]
Yea turns out ubuntu derivatives have a slightly different install directory, I'm working on a patch now!

**Comment by kotajacob** [comment]
Also have you run wal or wpg at least once with a wallpaper?

**Comment by kevinsmia1939** [comment]
I forgot to run wal first, so I run it. 
kevin@kevin-desktop:~/wal_steam$ wal -i "/home/kevin/Desktop/Figure/Wallpaper"
image: Using image /home/kevin/Desktop/Figure/Wallpaper/wallhaven-39597.jpg
wal: Generating a colorscheme...
wal: Generation complete.
]708;#202B04colors: Set terminal colors.
wallpaper: Set the new wallpaper.
export: Exported all files.
reload: Reloaded environment.
kevin@kevin-desktop:~/wal_steam$ sudo python3 wal_steam.py -w
Metro Wal found
Reading colors
Patching new colors
No file to remove
Wal colors are now patched and ready to go
If this is your first run you may have to 
enable Metro Wal Mod skin in steam then 
simply restart steam!

And I restart steam, however steam color does not change

**Comment by kevinsmia1939** [comment]
I am reinstalling steam if that help.

**Comment by kevinsmia1939** [comment]
Ok, it work now I got the color to appear, I forgot to change the interface. I don't think there is a bug. Just my lazy reading.

**Comment by kotajacob** [comment]
No worries, glad everything is working!
