### ISSUE TITLE
stray capital in file write reference

### ISSUE THREAD

**Issue by neeasade** [kotajacob/wal_steam#37]
FYI https://github.com/kotajacob/wal_steam/blob/master/wal_steam.py#L125

black45 is defined later on, not Black45 -- unsure if it's case sensitive or not.

**Comment by kotajacob** [comment]
That's an impressive catch, but surprisingly (I think) it actually has to be capitalized (will do more poking around tonight and report back). Basically the way skins are setup in steam is a mess and the actual variables attributed to different aspects of the UI are named very poorly. So I'm pretty sure that variable might actually be assigned as Black45 somewhere else in either metro or steam itself, but I'll look into it more tonight.

I'm currently working on a rather large rewrite of the whole colors.styles creation in the 1.2.0 branch which will implement a config file allowing users to pick which steam elements are colored with which of wal's colors. That way as I find new parts of the steam ui (or as valve adds more) they can be very easily customized and tested. (also it'll add windows support + clean up some of my sloppy code)

**Comment by neeasade** [comment]
I see -- I wish you luck! this is a nice idea/project, stumbled upon the issue while making a template to use in my dotfiles from your work.
