### ISSUE TITLE
Buttons missing from steam

### ISSUE THREAD

**Issue by Hnaguski** [kotajacob/wal_steam#53]
The buttons on the details pane are not showing up. They are probably being set to the same color as the background. You can see the difference in a screenshot from version 1.2.0 and 1.1.0

![4](https://ptpb.pw/xOo1.png)

![5](https://ptpb.pw/43pZ.png)

**Comment by kotajacob** [comment]
hmmm yea seems like they are.. you wouldn't happen to know the color variable for the buttons?

**Comment by kotajacob** [comment]
Fixed in 1.2.3 it was with the way the skin was being patched.
