### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by AccountOneOff** [kotajacob/wal_steam#56]
Category text isn't showing up with latest version. I'm on Ubuntu 17.04 if that matters.

Older version:
![old](https://i.imgur.com/ABoVLin.png)

Latest version:
![new](https://i.imgur.com/OKioMKt.png)

**Comment by kotajacob** [comment]
Strange I'll look into this now. Was the latest version the git master version or version 1.2.4?

**Comment by kotajacob** [comment]
I'm having a hard time reproducing this. Could you try running wal-steam -u to update the skin and cache to the latest version? I'm thinking maybe it was a strange bug caused by updating from an older version. I'll keep poking around though.

**Comment by AccountOneOff** [comment]
That might be it. Running `python3 wal_steam.py -u` worked.
