### ISSUE TITLE
Changing default font

### ISSUE THREAD

**Issue by AccountOneOff** [kotajacob/wal_steam#57]
Is there a way to change the font style? Changing the custom.styles file to Roboto or Ubuntu from Segoe UI doesn't seem to work. Also would it be possible to add an option for font choice when running the script?

**Comment by kotajacob** [comment]
That's a good idea yea I could make that an option in the script. It wont install the font, but I could at least make it be selected in the skin.

**Comment by kotajacob** [comment]
This was added with the release of version 1.3.1
