### ISSUE TITLE
Can't see game's title

### ISSUE THREAD

**Issue by AinsworthK** [kotajacob/wal_steam#58]
![steam_wal_issue](https://user-images.githubusercontent.com/21155336/30994468-b2a3151a-a479-11e7-902b-91fd153f2b4a.png)
Cannot see the game's title, this is a new issue, something update and this is the result.
I am not sure which package update cause this, i guess imagemagick.
I install it through AUR.

**Comment by kotajacob** [comment]
Can you run wal_steam --version quick? I'll see if I can replicate it

**Comment by kotajacob** [comment]
Another thing to try is wal-steam -u which will force update the cache and config files incase something broke during an update.

**Comment by AinsworthK** [comment]
`wal_steam -v` return: 
`Wal Steam 1.1.0`
I can't use `wal_steam -u`, this is the -h page:

Wal Steam

Usage:
  wal_steam.py (-w | -g)
  wal_steam.py (-h | --help)
  wal_steam.py (-v | --version)

Options:
  -w                   use wal for colors
  -g                   use wpg for colors
  -h --help            show this help message and exit
  -v --version         show version and exit`

**Comment by kotajacob** [comment]
Strange, that's a very old version. The current version is 1.2.4. Seems like the aur package isn't updating... I'll message the maintainer about it. In the mean time you could install the latest version with pip.

`pacaur -R python-wal-steam-git`
`sudo pip install wal-steam`
`wal-steam -u`

**Comment by AinsworthK** [comment]
it worked!
sorry , should have checked for the latest version first.

**Comment by kotajacob** [comment]
no worries! glad it's working now
