### ISSUE TITLE
Colors file missing

### ISSUE THREAD

**Issue by alizeegagnon** [kotajacob/wal_steam#59]
Hello, while running "wal-steam -w" I get the following output: `Wal Steam cache found  
Wal Steam config found  
Wal Steam skin found  
Reading colors  
Error: Colors file missing. Make sure you've run pywal/wpg before wal_steam  
`
I am a heavy wpg user so I have run it before. Where does wal-steam check for the colors file ?

**Comment by emctague** [comment]
Hi, as per the README, for wpg you should use the `-g` flag, not `-w`.

**Comment by alizeegagnon** [comment]
Hi, the "wal-steam -g" command does not give any error message thankfully ! However, the color is not applied on steam, even after restarting it. I use ubuntu 17.04 and installed via pip3.

**Comment by Hnaguski** [comment]
Hmm, are you sure you have the custom skin selected in steam? You can find skin settings under settings>interface. You should select "Metro 4.2.4 Wal_mod" from  the drop-down menu

**Comment by alizeegagnon** [comment]
I do have the "Metro 4.2.4 Wal_mod" option selected.

**Comment by kotajacob** [comment]
What distro are you running and what version of wal steam do you have installed (you can check by running wal_steam -v)

**Comment by alizeegagnon** [comment]
I am running Ubuntu 17.04 x86_64. I am using wal steam 1.2.4.

**Comment by alizeegagnon** [comment]
I am running Ubuntu 17.04 x86_64. I am using wal steam 1.2.4.

**Comment by kotajacob** [comment]
It seems like on some setups wal-steam is failing to create directories and then crashing when attempting to copy into them. This is most likely related to that so I'll update here once I get a fix working.
