### ISSUE TITLE
Regarding AUR Package - Cannot maintain it right now, dependency issues.

### ISSUE THREAD

**Issue by emctague** [kotajacob/wal_steam#63]
[The AUR package has been marked out of date](https://aur.archlinux.org/packages/python-wal-steam-git/) because the `python-pywal-git` package it depends on is nonexistent now. I am not currently in a position where I can easily fix this issue due to my current system setup (though I should be able to resolve further issues in the near future should any more arise.)

@kotajacob, could you perhaps replace it with `python-pywal` yourself, since you have maintainer access?

**Comment by emctague** [comment]
Update: I've managed to regain temporary access to my account and I believe I have resolved the problem on my own. I might need someone else to confirm that it works properly now, because I really have no way of knowing.

**Comment by kotajacob** [comment]
Thanks! I'll test it shortly, I'm working on fixing a few of the bugs with downloading metro right now anyway.

**Comment by SethBarberee** [comment]
@emctague, I can confirm that the AUR package works. I am using it right now and it worked just fine!

**Comment by emctague** [comment]
@SethBarberee Thank you for confirming that it still works!
