### ISSUE TITLE
Metro patch no longer available

### ISSUE THREAD

**Issue by Kaukoa** [kotajacob/wal_steam#65]
Hello,
I found that the given patch for metro is no longer available, which breaks the script.
I don't know if there is a mirror for the tested version, but the most recent seems to be available here:
https://steamcommunity.com/groups/metroforsteam/discussions/9/1621724915812034590/

**Comment by kotajacob** [comment]
Thanks for spotting this! I'll test that version tonight. If it doesn't work I can put up a mirror until I can work out updating to the new version.

**Comment by kotajacob** [comment]
I was able to replicate this, but unfortunately things came up in life and I wont be able to submit a fix until this next week is over. If during that time someone submits a PR I'll take a look and test it though.

**Comment by JohnHuddleston** [comment]
This issue is back, currently running into the following:
```
$ wal-steam -w                                         1 ↵ 
Wal Steam cache found
Downloading config file
Downloading Metro for steam
Downloading Metro patch
Error: downloading needed patch file. Check your connection and try again.
```

**Comment by kotajacob** [comment]
Can confirm. I just tested it and had the download fail. Then a few minutes later I tested it again and it worked. This is going to be really weird to debug. 

Maybe github is somehow blocking or limiting python request file downloads? Maybe the proper solution is to simply have wal_steam retry the download a couple of times before giving up?

**Comment by johnstt** [comment]
Hitting this same issue today :(

What do I do with the file from @Kaukoa 's first post to make it go?
Edit some of the python source?

**Comment by lplover** [comment]
So I ran into this issue, but running `wal-steam -w -d -u` worked perfectly fine.

**Comment by Tardog** [comment]
@JohnHuddleston Do you still plan to implement a retry approach for this issue? If you haven't found the time yet, I could give it a shot. Let's not have this lying around for too long.

**Comment by johnstt** [comment]
Or just ship the metro theme with this repo?

**Comment by JohnHuddleston** [comment]
I just started a new job and haven't had time to really dig into it, but I'm pretty sure I can help make it a little more robust.  The part of the script in question is on lines 246-253:

    try:
        opener = urllib.request.build_opener()
        opener.addheaders = [{'User-Agent', 'Mozilla/5.0'}]
        urllib.request.install_opener(opener)
        urllib.request.urlretrieve(METRO_PATCH_URL, METRO_PATCH_ZIP)
    except:
        print("Error: downloading needed patch file. Check your connection and try again.")
        sys.exit(1)

I work primarily in low-level imperative programming, so forgive the clunky C-like approach:


    patch_dl_attempts = 0
    patch_dld = False
    # MAX_PATCH_DL_ATTEMPTS could be handled by a global definition or could be configured with a flag
    while (patch_dl_attempts < MAX_PATCH_DL_ATTEMPTS) and not patch_dld: 
        try:
            opener = urllib.request.build_opener()
            opener.addheaders = [{'User-Agent', 'Mozilla/5.0'}]
            urllib.request.install_opener(opener)
            urllib.request.urlretrieve(METRO_PATCH_URL, METRO_PATCH_ZIP)
        except:
            patch_dl_attempts += 1
            print("Error: patch download failed.  [Attempt " + patch_dl_attempts + "]")
    if not patch_dld:
        print("Error: could not download patch file.")
        sys.exit(1)

**Comment by JohnHuddleston** [comment]
Okay, so my branch is useless.  For some reason if it fails, it's going to keep failing.  It goes through the entire urllib request sequence each time, but the only difference I see is between runs of the script.

**Comment by kotajacob** [comment]
Thanks again @JohnHuddleston I have now pushed out update 1.3.2 with the pull request added, both here on github and also on python's pip. This issue should be fully resolved as the useragent issue was fixed and a download retry parameter has been added (-a --attempts should you need it).
