### ISSUE TITLE
Update METRO_URL

### ISSUE THREAD

**Issue by sraysmith** [kotajacob/wal_steam#81]
Running the command wal_steam -w has produced the following error:

Wal Steam cache found
Wal Steam config found
downloading needed skin file
check your network connection

I opened up the wal_steam.py file and looked to see what the METRO_URL was:
"http://metroforsteam.com/downloads/4.3.1.zip"

I put that into the url in my browser and got a 404 not found.

I then went to https://metroforsteam.com and on the site there is a new Download page:
"https://github.com/minischetti/metro-for-steam/archive/v4.4.zip"

I substituted this url in place of the old one inside wal_steam.py METRO_URL and re-ran the command wal_steam -w and boom it downloaded the metro skin and patched the colors as expected!

I hope that this helps anyone who may be running into the same issue!

**Comment by sraysmith** [comment]
I should probably mention that if you currently have metro 4.3.1 installed and you run wal_steam -w, you will most likely not get an error because it was configured while the old url still worked. I tested this out on my laptop which has version 4.3.1 and I didn't get an error.

I came across this error on my desktop only because I did a clean install. I first attempted to transfer the 4.3.1 metro from my laptop steams/skins directory to my desktop and wal_steam wouldn't pick it up.

**Comment by sraysmith** [comment]
I know I might be rambling but most importantly the metro skin 4.4 is compatible with the new layout of Steam, which includes the library!!!

**Comment by Tardog** [comment]
> I know I might be rambling but most importantly the metro skin 4.4 is compatible with the new layout of Steam, which includes the library!!!

It seems the new library support is finally out of beta, then. :fireworks: Updating the metro skin version will likely solve #80 as well.

**Comment by Tardog** [comment]
@sraysmith I've opened a PR with the fix for this issue. Feel free to try the updated version of the script from #82 and test if it works for you.

**Comment by IHatedMyOldUsername** [comment]
The URL is still currently out of date, now up to 4.4: [Metro For Steam](https://github.com/minischetti/metro-for-steam/archive/v4.4.zip)
