### ISSUE TITLE
showing an error even tho i installed steam

### ISSUE THREAD

**Issue by ghost** [kotajacob/wal_steam#86]
Hi!
I just installed wal_steam and tried to theme steam using wal_steam command, but I can't for some reason and it's showing "Error: Steam install not found!" and "/opt/wal_steam/wal_steam.py:25: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.dir_util import copy_tree  # copytree from shutil is broken so use copy_tree" above it.
  I have no idea what that means so any help would be appreciated.
  
 My os = Arch linux
 Wal_steam version = 1.4
 Installed method = with aur
 Steam package = steam from arch linux mutilib rep
![2022-02-12-012722_1920x1080_scrot](https://user-images.githubusercontent.com/90143342/153652749-3e1cfdb2-7e2b-4f18-bd51-567b105d8bad.png)

**Comment by kaiartikkas** [comment]
how did you fix this?
